### ISSUE TITLE
Bug: different outputs on same command

### ISSUE THREAD

**Issue by cinocode** [jasypt/jasypt#9]
I have an oddity with jasypt encryption. I have a fresh release zip of 1.9.3 and i unzipped it.
I'm jusing openjdk8. I tested and have the same behaviour with opendk 11.

When I run this I get different outputs when I run it multiple times
`./encrypt.sh input=mysecret password=mykey`

First one:
```
----ENVIRONMENT-----------------

Runtime: Oracle Corporation OpenJDK 64-Bit Server VM 25.222-b05 



----ARGUMENTS-------------------

input: mysecret
password: mykey



----OUTPUT----------------------

nNDLbN8gZ+dMY3d/BYCKXhpXpXnMwvYD
```
Second one:
```
----ENVIRONMENT-----------------

Runtime: Oracle Corporation OpenJDK 64-Bit Server VM 25.222-b05 



----ARGUMENTS-------------------

input: mysecret
password: mykey



----OUTPUT----------------------

dSiM2FSBHQepBdnB9WOIYwZMeQa2UpPZ
```

I also tried quoting like this:
`./encrypt.sh input="mysecret" password="mykey"`

How can I get different passwords when running the same command with the same parameters?

**Comment by hokitorres** [comment]
This is the expected behaviour, because the default salt generator used by jasypt is `org.jasypt.salt.RandomSaltGenerator.`

When using a random salt generator, two encryption results for the same message will always be different (except in the case of random salt coincidence). This enforces security by difficulting brute force attacks on sets of data at a time and forcing attackers to perform a brute force attack on each separate piece of encrypted data.

Although not recommended, you can use no salt or a fixed salt to obtain always the same encrypted output. For example:

`./encrypt.sh input=mysecret password=mykey saltGeneratorClassName=org.jasypt.salt.ZeroSaltGenerator`

One final thought, if you are treating with passwords I encourage you to use jasypt for digesting them instead of encrypting them; a detailed explanation is available at http://www.jasypt.org/howtoencryptuserpasswords.html.

**Comment by cinocode** [comment]
Oh, okay thanks for the info. I was trying to find out why my password decryption did not work, but I guess it has to be a different issue.

I am using jasypt to encrypt database passwords among other things so a digest won't work there. But thanks for the tipp anyways.
